//! Caption files as they arrive: from disk, in whatever encoding, and back out
//! again unchanged.

use std::fs;

use ve_caption::{CaptionError, CaptionFormat};
use ve_core::{CaptionTrack, CaptionTrackId, Cue, CueId};
use ve_time::Ticks;

fn cue(raw: u64, start_ms: i64, end_ms: i64, text: &str) -> Cue {
    Cue::new(
        CueId::from_raw(raw),
        Ticks::from_millis(start_ms),
        Ticks::from_millis(end_ms - start_ms),
        text,
    )
}

#[test]
fn a_file_written_here_and_read_back_is_the_same_captions() {
    let dir = tempfile::tempdir().unwrap();
    let cues = [
        cue(1, 1_000, 4_000, "Hello there."),
        cue(2, 5_500, 7_000, "- Who's there?\n- It's me."),
        cue(3, 3_600_000, 3_602_500, "An hour in, to prove the hours are written."),
    ];

    for format in CaptionFormat::ALL {
        let path = dir.path().join(format!("out.{}", format.extension()));
        ve_caption::write(&path, &cues).unwrap();
        let back = ve_caption::read(&path).unwrap();
        assert!(back.warnings.is_empty(), "{format:?}: {:?}", back.warnings);
        assert_eq!(back.cues.len(), cues.len());
        for (original, parsed) in cues.iter().zip(&back.cues) {
            assert_eq!(parsed.span, original.range(), "{format:?}");
            assert_eq!(parsed.text, original.text, "{format:?}");
        }
    }
}

#[test]
fn cues_read_from_a_file_go_onto_a_track_in_order_and_free_of_overlaps() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("dialogue.srt");
    // Out of order, and with the first cue running into the second — which is
    // what a hand-corrected subtitle file routinely looks like.
    fs::write(
        &path,
        "2\n00:00:05,000 --> 00:00:07,000\nsecond\n\n\
         1\n00:00:01,000 --> 00:00:05,500\nfirst\n",
    )
    .unwrap();

    let file = ve_caption::read(&path).unwrap();
    let mut next = 100u64;
    let cues = file.into_cues(|| {
        next += 1;
        CueId::from_raw(next)
    });

    let mut track = CaptionTrack::new(CaptionTrackId::from_raw(1), "C1");
    track.replace_cues(cues);

    assert_eq!(track.len(), 2);
    assert_eq!(track.cues()[0].text, "first");
    assert_eq!(track.cues()[0].end(), Ticks::from_millis(5_000));
    assert!(track.invariants_hold());
}

#[test]
fn a_latin1_file_opens_with_its_accents_and_a_warning() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("legacy.srt");
    // "Café" in Latin-1: the é is a single 0xE9 byte, which is not valid UTF-8.
    let mut bytes = b"1\n00:00:01,000 --> 00:00:02,000\nCaf".to_vec();
    bytes.push(0xE9);
    bytes.push(b'\n');
    fs::write(&path, bytes).unwrap();

    let file = ve_caption::read(&path).unwrap();
    assert_eq!(file.cues[0].text, "Café");
    assert!(file.warnings.iter().any(|w| w.contains("Latin-1")), "{:?}", file.warnings);
}

#[test]
fn a_file_that_is_not_captions_is_refused_by_name_rather_than_read_as_empty() {
    let dir = tempfile::tempdir().unwrap();

    let wrong_extension = dir.path().join("notes.txt");
    fs::write(&wrong_extension, "1\n00:00:01,000 --> 00:00:02,000\nhello\n").unwrap();
    assert!(matches!(
        ve_caption::read(&wrong_extension),
        Err(CaptionError::UnknownFormat { .. })
    ));

    let empty = dir.path().join("empty.srt");
    fs::write(&empty, "").unwrap();
    assert!(matches!(ve_caption::read(&empty), Err(CaptionError::Empty { .. })));

    let missing = dir.path().join("nothing-here.srt");
    assert!(matches!(ve_caption::read(&missing), Err(CaptionError::Read { .. })));
}

#[test]
fn a_file_from_another_tool_survives_a_round_trip_through_verge() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("theirs.vtt");
    // Identifiers, a comment, markup and cue settings: everything a WebVTT file
    // from a captioning tool carries.
    fs::write(
        &path,
        "WEBVTT\n\n\
         NOTE generated by something else\n\n\
         1\n00:00:01.000 --> 00:00:03.000 align:middle\n<i>Music playing.</i>\n\n\
         2\n00:00:04.000 --> 00:00:06.000\n- Ready?\n- Ready.\n",
    )
    .unwrap();

    let file = ve_caption::read(&path).unwrap();
    // The settings are reported rather than kept, because there is nowhere to
    // put them; the markup is kept, because there is.
    assert!(file.warnings.iter().any(|w| w.contains("settings")), "{:?}", file.warnings);
    assert_eq!(file.cues[0].text, "<i>Music playing.</i>");

    let mut next = 0u64;
    let cues = file.into_cues(|| {
        next += 1;
        CueId::from_raw(next)
    });
    let out = dir.path().join("ours.vtt");
    ve_caption::write(&out, &cues).unwrap();

    let again = ve_caption::read(&out).unwrap();
    assert_eq!(again.cues.len(), 2);
    assert_eq!(again.cues[0].text, "<i>Music playing.</i>");
    assert_eq!(again.cues[1].text, "- Ready?\n- Ready.");
    // Nothing new to complain about the second time: the one thing that could
    // not be carried was already dropped, and the rest came back whole.
    assert!(again.warnings.is_empty(), "{:?}", again.warnings);
}
